#!/usr/bin/python3
"""
Script to run GTimeLog from the source checkout without installing
"""

import os
import sys

MIN_PYTHON = (3, 10)


def _ensure_supported_python() -> None:
    """Fail fast with a clear message if interpreter is too old."""
    if sys.version_info < MIN_PYTHON:
        current = f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}'
        required = f'{MIN_PYTHON[0]}.{MIN_PYTHON[1]}+'
        raise SystemExit(
            f'GTimeLog requires Python {required}, but got {current} at {sys.executable}.\n'
            'Use a newer Python 3 interpreter (3.10+).'
        )


_ensure_supported_python()

basedir = os.path.dirname(os.path.realpath(__file__))
pkgdir = os.path.join(basedir, 'src')
sys.path.insert(0, pkgdir)

from gtimelog import main  # noqa: E402

main()
