[tox]
envlist =
    py310,py311,py312,py313,py314,pypy3,lint,quality

[testenv]
setenv =
    LC_ALL=C
deps =
    freezegun
    pip
# The --no-deps is because I want to skip installing pygobject, it's not needed
# for tests.
skip_install = true
commands_pre =
    pip install --no-deps -e . --disable-pip-version-check --quiet
commands =
    python -m gtimelog.tests

[testenv:coverage]
deps =
    {[testenv]deps}
    coverage
    pytest-cov
    -cconstraints.txt
commands =
    python -m pytest --cov=src/gtimelog --cov-report=term-missing:skip-covered --cov-fail-under=40 -q

[testenv:py]
commands =
    python --version
    {[testenv]commands}

[testenv:lint]
deps = ruff
skip_install = true
commands_pre =
commands =
    ruff check src/ setup.py
    ruff format --check src/ setup.py

[testenv:quality]
deps =
    radon
    xenon
skip_install = true
commands_pre =
commands =
    xenon --max-absolute C --max-modules B --max-average A src/

[testenv:security]
deps = bandit[toml]
skip_install = true
commands_pre =
commands = bandit -c pyproject.toml -r src/ -q

[testenv:pre-commit]
deps = pre-commit
skip_install = true
commands_pre =
commands = pre-commit run -a
