UI_FILE = '/usr/share/gtimelog/gtimelog.ui'
PREFERENCES_UI_FILE = '/usr/share/gtimelog/preferences.ui'
ABOUT_DIALOG_UI_FILE = '/usr/share/gtimelog/about.ui'
SHORTCUTS_UI_FILE = '/usr/share/gtimelog/shortcuts.ui'
MENUS_UI_FILE = '/usr/share/gtimelog/menus.ui'
CSS_FILE = '/usr/share/gtimelog/gtimelog.css'
ICON_FILE = '/usr/share/gtimelog/gtimelog.png'
ICON_LARGE_FILE = '/usr/share/gtimelog/gtimelog-large.png'

LOCALE_DIR = '/usr/share/locale'
CONTRIBUTORS_FILE = '/usr/share/doc/gtimelog/CONTRIBUTORS.rst'
